version: '3.4'

services:
 



  registry:
    image: registry
    container_name: registry
    volumes:
      - ~/docker/registry:/var/lib/registry
      - ~/docker/registry/auth:/auth
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry_Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    restart: always
    privileged: true
    ports:
      - 5000:5000


# docker run --rm -ti xmartlabs/htpasswd mf Abcd12345678 > ~/docker/registry/auth/htpasswd