version: '3.4'

services:
  htpasswd:
    image: xmartlabs/htpasswd
    container_name: htpasswd
    command: ["mf abcd123456 > /htpasswd"]

  # registry:
  #   image: registry
  #   container_name: registry
  #   volumes:
  #     - ~/docker/registry/registry:/var/lib/registry
  #     - ~/docker/registry/auth:/auth
  #   environment:
  #     - REGISTRY_AUTH=htpasswd
  #     - REGISTRY_AUTH_HTPASSWD_REALM=Registry_Realm
  #     - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
  #   restart: always
  #   privileged: true
  #   ports:
  #     - 5000:5000