version: '3.4'

services:

  # 先执行 docker run --rm --entrypoint htpasswd httpd:2 -Bbn admin At9Ww3p4S8 > ~/docker/registry/auth/htpasswd 
  registry:
    image: registry
    container_name: registry
    volumes:
      - ~/docker/registry/registry:/var/lib/registry
      - ~/docker/registry/auth:/auth
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry_Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd  
      - REGISTRY_STORAGE_DELETE_ENABLED=true    
    restart: always
    ports:
      - 5000:5000

  redis:
    image: redis
    restart: always
    container_name: redis
    ports:
      - 6379:6379
    volumes:
      - ~/docker/redis/data:/data
    environment:
      - requirepass=At9Ww3p4S8
    command: [ "redis-server", "--appendonly", "yes" ]

  RabbitMQ:
    image: rabbitmq:management
    restart: always
    container_name: mq
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=mquser
      - RABBITMQ_DEFAULT_PASS=At9Ww3p4S8

  mysql:
    image: mysql
    restart: always
    container_name: mysql
    ports:
      - 3306:3306
    volumes:
      - ~/docker/mysql:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=At9Ww3p4S8

  pgsql:
    image: postgres
    restart: always
    container_name: pgsql
    ports:
      - 5432:5432
    volumes:
      - ~/docker/postgresql:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=At9Ww3p4S8

  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ~/docker/mongo:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: At9Ww3p4S8
    command: ["--auth"]
    
  # minio:
  #   image: minio/minio:latest
  #   restart: always
  #   container_name: minio
  #   ports:
  #     - 9000:9000
  #     - 9001:9001
  #   environment:
  #     - MINIO_ACCESS_KEY=adminminio
  #     - MINIO_SECRET_KEY=At9Ww3p4S8
  #   volumes:
  #     - /docker/minio:/data
  #     - /docker/minio/config:/root/.minio
  #   command: ["server /data --console-address :9001"]

  zookeeper:
    image: wurstmeister/zookeeper
    restart: always
    container_name: zookeeper
    volumes:
      -  ~/docker/zookeeper:/data
    ports:
      - 2182:2181
       
  kafka:
    image: wurstmeister/kafka
    restart: always
    container_name: kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.10.1.44:9092    
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    volumes:
      - ~/docker/kafka:/kafka
    depends_on:
      - zookeeper
