version: '3.4'

services:
  registry:
    image: registry
    container_name: registry
    volumes:
      - ~/docker/registry/registry:/var/lib/registry
      - ~/docker/registry/auth:/auth
    environment:
      - REGISTRY_AUTH=htpasswd
      - REGISTRY_AUTH_HTPASSWD_REALM=Registry_Realm
      - REGISTRY_AUTH_HTPASSWD_PATH=/auth/htpasswd
    restart: always
    privileged: true
    ports:
      - 5000:5000
    # command: ["docker run --rm --entrypoint htpasswd httpd:2 -Bbn admin 12345678 > ~/docker/registry/auth/htpasswd"]