#  github 自动部署 目录 .github/workflows 

name: .NET

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: dotnet publish a/c/c.csproj -c Release -o c
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with: 
        # registry: 1.1.1.1:5000
        # username: 1 
        # password: 1        
        username: 1
        password: ${{secrets.DOCKER_PASSWORD}}
    - name: Build and push Docker images a
      uses: docker/build-push-action@v4.0.0
      with:
        push: true
        tags: b/c:latest
        file: a/c/Dockerfile


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: SSH Remote Commands
      uses: appleboy/ssh-action@v0.1.7
      with: 
        host: 1
        username: root
        password: ${{secrets.SERVER_PASSWORD}}
        script: |
          docker run -d b/c:latest
    
    

    


